ontobio/assocmodel.py, ontobio/sparql/wikidata.py, tests/test_wd.py
=> Adding wikidata sparql. PTSD

ontobio/io/assocwriter.py, ontobio/obograph_util.py, ontobio/ontol.py, tests/resources/obsolete.json, tests/test_local_json.py
@dougli1sqrd this fixes the bug we say in the pipeline
=> handing of obsoletion

CHANGELOG.rst, bin/ontobio-assoc.py, docs/analyses.rst, ontobio/__init__.py
Better documenting enrichment analysis API
Driven by need to have a wrapper in galaxy:
https://github.com/galaxy-genome-annotation/docker-galaxy-genome-annotation/issues/16
=> WIP: Enrichment docs

.travis.yml, requirements.txt
=> pip install binary for scipy,

ontobio/config.py
https://github.com/biolink/ontobio/issues/64
and 
https://github.com/biolink/ontobio/issues/73
=> changing Session() to Config()

bin/ontobio-lexmap.py, ontobio/lexmap.py, ontobio/obograph_util.py, ontobio/ontol.py, tests/resources/lexmap_test.json
* added a test for running off local files
* added ability plug in custom word mappings (e.g. roman numerals to numbers)
* use a DiGraph rather than a (bidirectional) graph for xrefs
Note:
TBD, should this move to a separate repo/package?
=> Improvements to lexical mapping

tests/test_golr_associations.py
https://github.com/biolink/biolink-api/issues/92
Test a particular gene / term combo and ensure we get the expected negated results pack
Currently passes, so the api issue is in the rest/flask layer
=> Adding test for negation

bin/ontobio-parse-assocs.py
adding the --reports-md and --reports-json options to spit out the parse report in those formats
=> Report formats

ontobio/golr/beacon_query.py
- Performs case sensitive search, which is a problem. Need to implement
case insensitive search for keywords at least.
=> Initial resolution for issue #143

notebooks/GO_Functional_Similarity.ipynb, notebooks/GO_Functional_Similarity_using_AssocFiles.ipynb, notebooks/Mouse_Gene_Phenotypes.ipynb
=> go similarity

ontobio/golr/golr_query.py
PR for fixing issues addressed in https://github.com/biolink/biolink-api/issues/158
@nathandunn
To test, simply clone biolink-api codebase and in `requirements.txt` simply change:
```
ontobio>=0.2.33
```
with
```
git+git://github.com/deepakunni3/ontobio.git@issue-158
```
and run:
```
pip install -r requirements.txt
```
=> add 'reference', 'qualifier', 'is_redundant_for' and 'type' for GOlr query

ontobio/golr/golr_query.py
@nathandunn FYI
Here is the Gist of the JSON response: https://gist.github.com/deepakunni3/dd0698b4d2424c776aa89c5840a025c7
=> Fix condition for checking select_fields before adding GOlr specific fields

ontobio/io/gafparser.py
=> Enforce F/P/C aspect ONLY in GO

ontobio/golr/golr_query.py
For autocomplete and search, we want the ability to filter given a list of prefixes.  This use case is required for the gamma reasoner.
=> Support a list of prefix filters (pos and neg)

conf/config.yaml, ontobio/config.yaml, ontobio/golr/golr_query.py, tests/resources/test-config.yaml
=> update AmiGO Solr URL

bin/validate.py, ontobio/assoc_factory.py, ontobio/ecomap.py, ontobio/golr/golr_associations.py, ontobio/golr/golr_query.py, ontobio/io/assocparser.py, ontobio/neo/scigraph_ontology.py, ontobio/util/user_agent.py, tests/test_golr_search.py
This PR adds `User-Agent` to headers of all HTTP requests made by Ontobio. See #190 
This PR also tidies up the way pysolr is instantiated in `golr_query.py`.
=> Set user-agent for requests made by ontobio

ontobio/io/assocparser.py, ontobio/io/gafparser.py, ontobio/io/gpadparser.py, ontobio/io/hpoaparser.py, tests/test_gafparser.py, tests/test_parse_ids.py
https://github.com/biolink/ontobio/issues/205
=> bad ids in pipe fields now filter out the line. Tests for the new pipe logic

ontobio/io/assocparser.py, ontobio/io/gafparser.py, ontobio/io/qc.py, tests/resources/truncated-pombase.gaf, tests/test_gafparser.py, tests/test_qc.py
https://github.com/geneontology/go-site/issues/710
=> fixing some tests, filtering IEAs after a year old with tests

ontobio/ontol.py, tests/test_wd_ontol.py
No rush on this. Just wondering what you guys think about it.
As far as I can tell, this method isn't being used anywhere but @valearna was thinking about using it in his [agr_genedescriptions](https://github.com/alliance-genome/agr_genedescriptions) code.
=> Potentially fixing issue #187 for parent_index method

tests/resources/alt_id_test.json, tests/test_alt_id.py
=> basis for test for alt_id issue

.gitignore, ontobio/analysis/semsim.py, ontobio/assoc_factory.py, ontobio/io/qc.py, tests/test_assocfactory.py
- Added a test for this case
- Gitignored `.pytest_cache/` which is generated when running tests
=> create_from_file chooses parser by file suffixes if fmt is None

ontobio/ontol.py
For issue #234 . Let me know if the getLogger usage affects anything huge.
=> Issue 234 - ontol logging stuff

ontobio/golr/golr_query.py
Fix a bug introduced into golr_query when adding relationship_type parameter to GolrAssociationQuery class, which in turn was affecting biolink API slimmer calls.
=> Fix slimmer bug

ontobio/golr/golr_query.py, ontobio/io/ontol_renderers.py, ontobio/sparql/sparql_go.py
Some GOlr queries will probably be later replaced to more correctly use GolrSearchQuery.
Some additional SPARQL queries.
PR required for following PR in BioLink
=> Required for new GO queries in BioLink

ontobio/io/assocparser.py
Sorry this didn't get in tonight. Probably would have been hard either way.
=> quick patch for MGIs double prefix issue

ontobio/sim/annotation_scorer.py, ontobio/sim/api/interfaces.py, ontobio/sim/api/owlsim2.py, ontobio/sim/api/owlsim3.py, ontobio/sim/phenosim_engine.py, ontobio/sim/sim_engine.py, tests/test_owlsim2_int.py
Adds limit parameter for owlsim and interfaces, fixes integration test, and some lint warnings.
=> Add limit for owlsim queries, lint fixes

ontobio/config.yaml, ontobio/sim/phenosim_engine.py, tests/test_owlsim2_int.py
Fixes bug when comparing against multiple profiles
=> small bug fixes, increase owlsim2 timeout

ontobio/io/assocparser.py, ontobio/io/gafparser.py
Will look like in *-report.md:
> !gaf-version: 2.0  
> !Project_name: WormBase  
> !Contact Email: help@wormbase.org
=> header now added into file report

bin/validate.py
This will also throw an error if validate finds a relative path but isn't supplied a base path:
Path in gocam config:
`source: ./products/annotations/noctua_mgi.gpad.gz`
Note in the command the option `--base-download-url` is not supplied
```
$ python bin/validate.py produce gocam -m ~/lbl/geneontology/go-site/metadata/ -t target/ -o go-ontology.json
Making products gaf, gpi.
Products will go in /Users/edouglass/lbl/biolink/ontobio/target
Found gocam metadata at /Users/edouglass/lbl/geneontology/go-site/metadata/datasets/gocam.yaml
Loading ontology: go-ontology.json...
Found noctua_mgi
Downloading source gaf to /Users/edouglass/lbl/biolink/ontobio/target/groups/gocam/noctua_mgi-src.gaf.gz
Error: Option --base-download-url was not specified and the config url …
```
=> validate.py gets an option to pass a base URL for relative download paths

ontobio/ontol_factory.py
=> Generate SHA256 from file contents

bin/validate.py, ontobio/io/assocparser.py, ontobio/io/gafparser.py
Upgrades column 1 from synonyms in dbxrefs yaml
=> Gosite 799 upgrade col1

ontobio/rdfgen/assoc_rdfgen.py, ontobio/rdfgen/relations.py
For https://github.com/biolink/ontobio/issues/321
=> set of relations used instead of searching the ontology for URIs

ontobio/io/assocparser.py, ontobio/io/gafparser.py, ontobio/io/qc.py, tests/test_parse_ids.py
I need to write a couple tests for this new function, but then will be actual ready. Take a look in the meantime.
=> removing group specific reference IDs

ontobio/io/gafparser.py
For https://github.com/biolink/ontobio/issues/329
=> removing the skip line for soft gorule checks

ontobio/golr/golr_query.py
This bug was causing some of the Golr queries to fail
=> Filter for None before calling join in golr_query

ontobio/io/gaference.py, ontobio/model/association.py, ontobio/rdfgen/relations.py, tests/resources/test.inferences.json, tests/test_gaference.py
https://github.com/biolink/ontobio/issues/220
Main work is in ontobio/io/gaference.py
=> module for taking a gaferncer output json file and enable checking taxons and generating gaf inferences

docs/installation.rst, docs/ontologies_advanced.rst, ontobio/assoc_factory.py, ontobio/config.py, ontobio/config.yaml, ontobio/ecomap.py, ontobio/ontol_factory.py, ontobio/sim/api/owlsim2.py, ontobio/sparql/sparql_ontol_utils.py, ontobio/sparql/sparql_ontology.py, ontobio/sparql/wikidata.py
Reverts biolink/ontobio#346
See https://github.com/biolink/ontobio/issues/355
=> Revert "Introduced "ignore_cache" flag in ontobio/config.yaml (defaults to 'False') "

.travis.yml, bin/validate.py, ontobio/io/assocparser.py, ontobio/io/gaference.py, ontobio/io/gafparser.py, ontobio/io/qc.py, ontobio/ontol_factory.py, tests/test_qc.py
This will require pipeline changes take affect. PR for go-site on its way.
=> using gaferencer output to perform taxon checks in rule 13

bin/materialize.py, ontobio/io/assocwriter.py, ontobio/rdfgen/relations.py, setup.py
python bin/materialize.py infer --ontology go-ontology.json --gaf tmgi.gaf --target mgi_enables_inferred.gaf
=> WIP initial draft of enables o has part annotation inference

ontobio/io/assocparser.py, ontobio/io/gafparser.py, ontobio/io/parsereport.py
For https://github.com/geneontology/go-site/issues/1161
=> reports changed so that rules with 0 errors show up

ontobio/io/qc.py, tests/test_qc.py
For https://github.com/geneontology/go-site/issues/1174
=> adding gorule 46 to line by line check

bin/validate.py, ontobio/io/assocparser.py, ontobio/io/gafparser.py, ontobio/io/qc.py, tests/resources/errors.gaf, tests/test_gafparser.py, tests/test_qc.py
For https://github.com/geneontology/go-site/issues/1118
=> Gorule 30 update

Makefile, ontobio/ontol.py, tests/test_ontol.py
For https://github.com/biolink/ontobio/issues/332
=> fix key error issue during missing node for ontol

ontobio/io/qc.py, tests/test_qc.py
For https://github.com/biolink/ontobio/issues/383
=> adding a test and fixing impl of gorule 11

bin/validate.py, ontobio/io/assocparser.py, ontobio/validation/metadata.py, ontobio/validation/tools.py
For https://github.com/biolink/ontobio/issues/386
=> adding some files for a refactor for the validate.py script for future work

ontobio/io/qc.py, tests/test_qc.py
https://github.com/biolink/ontobio/issues/388
@deepakunni3 Will we need a release for this? Or is master sufficient for now?
=> fixing bug with gorule46 and passing in no ontology

bin/validate.py
For https://github.com/biolink/ontobio/issues/392
=> validate fix

bin/validate.py, ontobio/io/assocwriter.py
for https://github.com/geneontology/pipeline/issues/142
=> fixing blank line issue in products

ontobio/golr/golr_query.py, ontobio/obograph_util.py, tests/resources/expected/test-evidence.json, tests/unit/resources/solr/expected/clinical-mod.json
Some small changes to help with the UI dev:
- Publications now defaults to [] instead of None/null
- Use curies in evidence table instead of IRIs for equivalent IDs
closes https://github.com/biolink/ontobio/issues/318
=> Use curies in ev table, default publications list

ontobio/io/qc.py
for https://github.com/biolink/ontobio/issues/410
=> skipping gorule-0000015 if not ontology provided

ontobio/io/assocparser.py, ontobio/io/gafparser.py, ontobio/io/gpadparser.py, ontobio/io/qc.py, ontobio/rdfgen/relations.py
Fixing https://github.com/biolink/ontobio/issues/416
=> fixing curie relation issue from #416

ontobio/io/gafparser.py, ontobio/io/qc.py
=> Go site 1376 ecosyc exception

ontobio/__init__.py
For some reason the logging configuration I was using before failed after all the merges. Here is a more robust version. I'm going to just merge this through once travis passes
=> making logging setup more robust

bin/validate.py
for https://github.com/biolink/ontobio/issues/424
=> fixing potential key error in verbose logging

ontobio/io/qc.py, tests/test_qc.py
For https://github.com/geneontology/go-site/issues/882.
=> extending rules for gorule 13

ontobio/io/qc.py, tests/test_qc.py
For https://github.com/geneontology/go-site/issues/1420
=> setting gorule 30 to be soft/warn

ontobio/io/qc.py, tests/resources/test.inferences.json, tests/test_qc.py
For https://github.com/geneontology/go-site/issues/1444
=> adding rule 13 test case for IEA, adding IEA to non exp eco ids

ontobio/io/assocparser.py, ontobio/io/gafparser.py, ontobio/io/gpadparser.py, ontobio/io/qc.py, tests/test_qc.py
Work on geneontology/go-site#1456
=> Adjust window expansion for IEAs in GAF QC

ontobio/config.py, requirements.txt, setup.py
fixes https://github.com/biolink/ontobio/issues/448
=> add require_tld=False to EndpointSchema

ontobio/validation/rules.py
For https://github.com/biolink/ontobio/issues/453
=> setting PASS variant of example type enum to pass, rather than fail

bin/ontobio-parse-assocs.py, ontobio/__init__.py
Getting this into a release hopefully for use in GO pipeline.
=> Option to allow IBAs for geneontology/go-site#1531

ontobio/io/assocparser.py, ontobio/io/qc.py, tests/test_qc.py
This is a remake of https://github.com/biolink/ontobio/pull/326
For issue https://github.com/geneontology/go-site/issues/1063
I will close the above PR in favor of this one.
=> adding gorule55 in qc and a test

ontobio/io/assocwriter.py, tests/test_assoc_writer.py
For https://github.com/biolink/ontobio/issues/470
=> qualifiers from gpad to gaf that are outside the gaf spec just blank out the field

ontobio/io/gpadparser.py
For https://github.com/biolink/ontobio/issues/475
=> gpad now correctly sets the relation when parsing

ontobio/io/assocwriter.py, ontobio/io/gpadparser.py, ontobio/model/association.py, tests/test_assoc_writer.py, tests/test_gpad_writer.py
This is the GPAD 2.0 writer side of things! First go-around anyway.
=> gpad 2.0 writer for geneontology/go-site#1453

bin/ontobio-parse-assocs.py, ontobio/__init__.py, ontobio/io/__init__.py, ontobio/io/assocparser.py, ontobio/io/assocwriter.py, ontobio/io/entityparser.py, ontobio/io/gafparser.py, ontobio/io/gpadparser.py, ontobio/model/association.py, ontobio/model/collections.py, tests/resources/no-version.gaf, tests/test_collections.py, tests/test_gpad_parser.py
This is the bit that will help thread through arbitrary Annotation data along with Bio Entity data. Drawing when the three of us talked about this: https://docs.google.com/drawings/d/1QSurx_SG50LXUpVRUYZVWNkSF8szGrGh5DpBtXRzKGo/edit
=> Association collections

Makefile
Adding clinical modifier test back now that we've renewed our certs, closes #452
=> add clinical mod test back

ontobio/golr/golr_query.py
Use self._use_amigo_schema(object_category) to determine if the query will end up using the amigo golr
=> Fix slimmer sort bug

bin/ontobio-parse-assocs.py
For https://github.com/biolink/ontobio/issues/494
=> adding version option to convert subcommand in ontobio-parse-assocs

bin/validate.py, ontobio/validation/metadata.py
for https://github.com/biolink/ontobio/issues/496
=> protect against a missing key in dataset yaml

ontobio/io/ontol_renderers.py, ontobio/io/qc.py, ontobio/obograph_util.py, ontobio/ontol.py, tests/test_sparql_connection.py
=> Fix networkx usage

ontobio/ontol.py, tests/test_ontol.py
=> Ontology.merge copies logical defs and property chain axioms

ontobio/io/gafparser.py, ontobio/ontol.py, tests/test_gafparser.py
gorule-0000059 to upgrade gaf 2.1 qualifiers into better relations based on GO Term.
https://github.com/geneontology/go-site/issues/1558
=> Go-site issue 1558 gorule 59

ontobio/model/association.py, tests/test_assoc_writer.py
For https://github.com/biolink/ontobio/issues/521
=> correcting the output formatter for extensions in gaf 2.2

ontobio/io/assocparser.py, ontobio/io/gpadparser.py, ontobio/model/association.py, tests/test_assoc_writer.py, tests/test_gpad_parser.py
@dougli1sqrd Here's my first go! Let me know if I should add more tests. Do you think we should make some sort of class for this new `properties: List[Tuple[str, str]]` data structure?
=> Issue #513 - change annotation props from dict to list of 2-tuples

ontobio/io/assocparser.py, ontobio/io/gpadparser.py, ontobio/model/collections.py
For https://github.com/biolink/ontobio/issues/525
=> report message calls make sure to wrap taxon objects as strings

ontobio/rdfgen/gocamgen/README.md
Basically copied my email reply to @sierra-moxon into a `.md`. @dougli1sqrd @kltm Let me know if any clarification could be added to this.
=> Added README.md for gocamgen translation

bin/ontobio-expand-tsv.py, ontobio/tsv_expander.py, tests/resources/data_table.tsv, tests/test_expand_tsv.py
@deepakunni3 @kshefchek - example of a fast method of enriching a tsv - e.g. kgx - with ontologies, for loading into a denormalized solr store or similar
=> expand a TSV using ontology lookups

ontobio/io/qc.py, tests/test_qc.py
'Nother round of rule 61
Discussion here: https://github.com/geneontology/go-site/issues/1658#issuecomment-795960771
=> update gorule 61 again

ontobio/io/assocparser.py, ontobio/io/gaference.py, ontobio/io/gpadparser.py, ontobio/model/association.py, tests/test_gpad_parser.py
https://github.com/geneontology/pipeline/issues/206
=> updates needed for new pipeline kernel, small bugifxes

ontobio/rdfgen/gocamgen/gocamgen.py
Should fix geneontology/gocamgen#87.
This will emit comments from GPAD annotation properties `comment` field to the translated GO-CAM.
=> Emit comments from GPAD annotation properties

ontobio/io/assocparser.py, ontobio/io/gafparser.py
small fix in the ruleset, for https://github.com/biolink/ontobio/issues/544
Will release once this hits master
=> Issue 544 rule set bugfix

ontobio/rdfgen/relations.py
Just adds the relations needed to correctly validate MGI annotation extensions.
=> Update relations.py for issue #548

ontobio/rdfgen/gocamgen/gocamgen.py
Fixes an issue where "Assigned By" isn't appearing for MOD import annotations in ART or Noctua Form.
=> Emit providedBy to all individuals; for geneontology/gocamgen#89

requirements.txt
See https://github.com/biolink/ontobio/issues/554
=> anchor networkx to 2.3

ontobio/sim/api/owlsim2.py
Since owlsim only ranks results in order of phenodigm score, we need to increase the limit when using other methods to make
sure we're able to rerank accurately.  Otherwise, we end up giving different results depending on the limit param, see https://github.com/biolink/biolink-api/issues/374
fixes https://github.com/biolink/biolink-api/issues/374
=> increase owlsim limit to accurately rank non phenodigm metrics

ontobio/io/entitywriter.py, tests/test_gpiwriter.py
Should fix geneontology/go-site#1681.
=> Go site 1681 gpi header newline

ontobio/io/gafgpibridge.py, tests/test_gafparser.py
Should fix geneontology/go-site#1682.
=> Go site 1682 gpi obj type label

bin/ontobio-parse-assocs.py, ontobio/io/assocparser.py
=> Fixing ontobio-parse-assocs to run all rules; for #558

bin/validate.py
=> Fix default --rule-set handling for #564

Makefile, ontobio/rdfgen/gocamgen/collapsed_assoc.py, ontobio/rdfgen/gocamgen/errors.py, ontobio/rdfgen/gocamgen/gocamgen.py
=> Fix circular reference for #568; add test_gocamgen to travis

ontobio/rdfgen/gocamgen/gocamgen.py, tests/test_gocamgen.py
=> Activate Ref Pref and add test for geneontology/gocamgen#31

bin/validate.py, ontobio/rdfgen/gocamgen/gocam_builder.py, ontobio/rdfgen/gocamgen/gocamgen.py
For geneontology/gocamgen#91.
To use, just need to set `--modelstate` or `-s` to `production`. Default is `development`.
=> Param to set modelstate for geneontology/gocamgen#91

bin/validate.py, ontobio/io/gafparser.py, ontobio/io/gpadparser.py
For geneontology/pipeline#239.
I also refactored a few of the simple unzipping operations throughout `validate.py`.
=> Find and merge other GPIs for a dataset. For geneontology/pipeline#239

bin/ontobio-assoc.py, ontobio/golr/golr_query.py, ontobio/io/qc.py, ontobio/rdfgen/gocamgen/collapsed_assoc.py, tests/test_qc.py
=> Fix hard-coded ECO codes

ontobio/io/gafparser.py, tests/test_gafparser.py
=> Bump GAF relation validate to before CURIE lkp - issue #591

ontobio/model/biomodel.py, ontobio/sim/api/owlsim2.py, ontobio/util/scigraph_util.py, tests/unit/test_biomodel.py
Makes optional attributes explicitly Optional on biomodel dataclasses, this fixes https://github.com/monarch-initiative/monarch-ui/issues/472
=> Patch to fix publication bug on the ui

ontobio/rdfgen/gocamgen/gocamgen.py
=> Emit creation date on Evidence individual

ontobio/rdfgen/gocamgen/gocamgen.py
=> Pass full evidence object to add_evidence.

ontobio/rdfgen/gocamgen/gocamgen.py, ontobio/rdfgen/relations.py
=> Convert relations to has_primary_input for #613

ontobio/ecomap.py, ontobio/io/gpadparser.py, ontobio/model/association.py, tests/test_assoc_writer.py, tests/test_gpad_parser.py
=> Use gaf-eco-mapping-derived.txt in EcoMap

ontobio/model/association.py
Not sure why this is hard-coded and not somehow pulling from a dynamic SO, but adding to get moving quickly on https://github.com/geneontology/go-site/issues/1876
=> Add additional SO terms to the hard-coded map

.github/workflows/make-tests.yaml, ontobio/io/qc.py, tests/test_qc.py
Implemented this change with @mugitty. We will merge and release to get into GO pipeline.
=> Change IEA expiration date for geneontology/pipeline#317

ontobio/io/assocparser.py, ontobio/io/gafparser.py, ontobio/io/gpadparser.py, tests/test_gafparser.py, tests/test_gpad_parser.py
=> For geneontology/go-site#844

ontobio/io/qc.py, tests/test_qc.py
For https://github.com/geneontology/go-site/issues/895 - Check if annotated term is in the complex closure
=> Check if annotated term is in the complex closure

ontobio/io/qc.py, tests/test_qc.py
=> For geneontology/go-site#895 fix list bug

ontobio/io/qc.py, tests/test_qc.py
=> For geneontology/go-site#1519 - exclude annotations with source = GOC 

ontobio/io/qc.py, tests/test_qc.py
For geneontology/go-site#2030 - Added check for unique taxons
=> For geneontology/go-site#2030

ontobio/io/qc.py, tests/test_qc.py
=> For #2038 Changed to error from warning

ontobio/io/gafparser.py
GORULE:0000001 - GAF line should have DB Object symbol in column 3
=> For #2049 Added check for DB object symbol
