- Makefile
- README.md
- bin/ogr.py
- conf/config.yaml
- docs/inputs.rst
- ontobio/io/ontol_renderers.py
- ontobio/neo/scigraph_ontology.py
- ontobio/ontol.py
- ontobio/ontol_factory.py
- ontobio/sparql/sparql_ontology.py
- tests/test_remote_scigraph.py
This PR adds an adapter for OB to transparently query a remote scigraph instance as if it were a local ontology.
For more background see: http://ontobio.readthedocs.io/en/latest/inputs.html
> Adding a SciGraph adapter

- ontobio/golr/golr_query.py
I cleaned up the `subject_or_object_ids` filtering code, and added a `subject_or_object_category` filter as well. The category filter is not working perfectly well (see issue: https://github.com/biolink/ontobio/issues/52), though it may still be useful to have an imperfect implementation.
> Knowledge beacon

- ontobio/golr/golr_query.py
This allows you to use `GolrAssociationQuery` as such:
```python
q = GolrAssociationQuery(
subject='DOID:9744'
non_null_fields=['relation', 'subject']
)
results = q.exec()
```
Now `results` will not contain any associations that do not have a relation or a subject.
Related to this issue: https://github.com/biolink/biolink-api/issues/88
> Added non_null_fields to GolrAssociationQuery

- ontobio/io/entityparser.py
- tests/test_gpiparser.py
This fixes the immediate zfin issues. Fills in missing columns with the empty string. If it's more than 3 missing it'll still fail. 
Zfin now spits out line errors, rather than just crashing immediately.
> more robust column values decomposition

- bin/ontobio-parse-assocs.py
- ontobio/io/assocparser.py
- ontobio/io/assocwriter.py
Ontobio just passes on spaces in the offending space in ids in relation expressions. This fixes this by simply replacing spaces with underscores. This won't create a correct id, as the space in the id is ultimately from upsteam. But this allows ontobio parsed gafs to then be turned into ttl at all, and ingested by blazegraph. We can correct the underscores with subsequent blazegraph loads (with the corrected ids), or with sparql queries later.
> uses assocwriter to write parsed validated gaf. parser replaces space s in relationship expressions with underscore

- ontobio/golr/golr_query.py
The fix in PREFIX_NORMALIZATION_MAP actually didn't help since WormBase is needed for the homolog search, but WB for the GO annotations
> WB for WormBase is too agressive as it changes the gene ID too

- ontobio/io/assocparser.py
- ontobio/rdfgen/assoc_rdfgen.py
Temporary fix for bad IDs in GAFs. 
In messages, @cmungall  suggested we repair on the fly, but looking at the code, that's not how the strategy works at the moment. In order to get the run to work, this will stick with the throw-out-bad-line strat until we work with a different strategy. 
We can also make the rdfgen process a little more resilient to bad ids. If we want that in this, we can make that happen. But as it stands, this fixes the rdfgen issues.
> throws out lines with bad chars in ids

- Makefile
- ontobio/io/assocparser.py
- ontobio/io/gafparser.py
- ontobio/io/qc.py
- tests/resources/goslim_generic.json
- tests/test_qc.py
For https://github.com/biolink/ontobio/issues/154 and the future.
This provides an easy way to implement go rules that act on an annotation by annotation level to be checked by the gaf parser. This model can be extended if needed to other kinds of rule checks. The triggering of the QC in the gaf parser is small and easy to use. 
To add a Go Rule, just make a class like the GoRule08 existing example. This slightly mirrors the rule json format in go-site.
> gorule infrastructure and gorule 08 implementation

- ontobio/golr/golr_query.py
This PR aims at using AmiGO schema-specific evidence fields in Solr query.
A good example is when there is a call to the biolink-api endpoint `bioentityset/slimmer/function`.
```
https://api.monarchinitiative.org/api/bioentityset/slimmer/function?&slim=GO:0003824&slim=GO:0004872&slim=GO:0005102&slim=GO:0005215&slim=GO:0005198&slim=GO:0008092&slim=GO:0003677&slim=GO:0003723&slim=GO:0001071&slim=GO:0036094&slim=GO:0046872&slim=GO:0030246&slim=GO:0003674&slim=GO:0008283&slim=GO:0071840&slim=GO:0051179&slim=GO:0032502&slim=GO:0000003&slim=GO:0002376&slim=GO:0050877&slim=GO:0050896&slim=GO:0023052&slim=GO:0010467&slim=GO:0019538&slim=GO:0006259&slim=GO:0044281&slim=GO:0050789&slim=GO:0042592&slim=GO:0007610&slim=GO:0008150&slim=GO:0005576&slim=GO:0005737&slim=GO:0005856&slim=GO:0005739&slim=GO: …
```
> use AmiGO schema-specific evidence fields in Solr query

- ontobio/io/gafparser.py
- tests/resources/errors.gaf
- tests/test_gafparser.py
For https://github.com/geneontology/go-site/issues/563
> throwing out lines with GO_REF:33 in the references column

- notebooks/Phenotype_Enrichment.ipynb
- ontobio/rdfgen/assoc_rdfgen.py
NOTE: this is a temporary measure. We will build the go json ld context as part of the pipeline in future
See https://github.com/geneontology/go-site/issues/617
> Use correct go_context jsonld file in gaf->go-cam

- ontobio/golr/golr_query.py
Add `numFound` into the response payload such that its available for association queries made by the biolink-api.
This PR aims to fix https://github.com/biolink/biolink-api/issues/155
@cmungall @putmantime
> Include result hits as 'numFound' in payload returned by GolrSearchQuery and GolrAssociationQuery

- bin/rdfgen.py
- bin/validate.py
- ontobio/__init__.py
- ontobio/io/assocparser.py
- ontobio/io/assocwriter.py
- ontobio/io/entitywriter.py
- ontobio/io/gafgpibridge.py
- ontobio/io/gafparser.py
- ontobio/ontol_factory.py
- ontobio/rdfgen/assoc_rdfgen.py
- setup.py
The main change here is to add a validate.py script in the bin directory. This orchestrates much of what the old makefile did. You give validate the target directory, the metadata directory, and which group to produce data from:
First it finds the <group>.yaml. For each gaf dataset in the group yaml, download the source gaf, and run it through the gaf validation step, producing the noiea, and standard reports we all know and love. We call this <dataset>_valid.gaf.
Then we produce a gpi file and a gpad file from the validated gaf.
Next we check if there is a corresponding paint_<group> dataset. If so, we download the src paint gaf, validate it, but use the earlier GPI to correct entitites in the paint gaf. 
Once we have a valdiated paint gaf, we do the "merge", where we take validated …
> Paintmerge 591

- ontobio/io/gafparser.py
- tests/resources/errors.gaf
- tests/test_gafparser.py
also for taxon
For context see https://github.com/geneontology/go-site/issues/639
> Explicitly flag errors and skip lines if local id or idspace not set

- bin/validate.py
- ontobio/__init__.py
The bug only happens if the dataset name has more than one underscore, and also has an accompanying paint gaf. This is a simple `split` function call change.
> Naming error bugfix

- ontobio/golr/golr_query.py
Fix for https://github.com/biolink/biolink-api/issues/201
Adding the flexibility of selecting a closure depending on a given `relationship_type`
> Add relationship_type argument to GolrAssociationQuery

- ontobio/golr/golr_query.py
- tests/unit/resources/solr/autocomplete-nocat-expect.json
- tests/unit/resources/solr/autocomplete-nocat.json
- tests/unit/test_golr_search_query.py
Currently querying solr docs without a category returns a 500, for example:
https://api-dev.monarchinitiative.org/api/search/entity/autocomplete/foo?rows=20&start=0
This should be fixed upstream in scigraph or the solr loader, but in the meantime this should be handled by ontobio.
> Handle solr docs without a category

- requirements.txt
This ensures that by default shortest URIs are chosen if multiple
contractions are possible
> increase version of prefixcommons

- bin/validate.py
I hadn't set the `label` to the filename of the incoming gaf for some reason. With it set, you can see in https://github.com/biolink/ontobio/blob/master/ontobio/rdfgen/assoc_rdfgen.py#L62 that with the label definitely set, we add an rdfs:label triple. 
Tested with a previously broken MGI, we get the label.
> making sure all gaf cam models have rdfs:labels

- ontobio/config.py
- ontobio/config.yaml
Restrict the results (e.g. annotations) based on provided taxons (if any)
> Adding taxon_restriction features (also required for new BioLink version)

- ontobio/sim/api/owlsim2.py
- tests/resources/owlsim2/mock-owlsim-noresults.json
- tests/test_phenosim_engine.py
Fixes bug that occurs when no results are returned by owlsim, for example:
https://api.monarchinitiative.org/api/sim/search?id=HP:0000006&id=HP:0000174&id=HP:0000194&id=HP:0000218&id=HP:0000238&id=HP:0000244&id=HP:0000272&id=HP:0000303&id=HP:0000316&id=HP:0000322&id=HP:0000324&id=HP:0000327&id=HP:0000348&id=HP:0000431&id=HP:0000452&id=HP:0000453&id=HP:0000470&id=HP:0000486&id=HP:0000494&id=HP:0000508&id=HP:0000586&id=HP:0000678&id=HP:0001156&id=HP:0001249&id=HP:0002308&id=HP:0002676&id=HP:0002780&id=HP:0003041&id=HP:0003070&id=HP:0003196&id=HP:0003272&id=HP:0003307&id=HP:0003795&id=HP:0004209&id=HP:0004322&id=HP:0004440&id=HP:0005048&id=HP:0005280&id=HP:0005347&id=HP:0006101&id=HP:0006110&id=HP:0009602&id=HP:0009773&id=HP:0010055&id=HP:0010669&id=HP:0011304&taxon=7227
> Fix bug when no results are returned

- ontobio/model/similarity.py
- ontobio/sim/api/owlsim2.py
- ontobio/sim/phenosim_engine.py
- tests/resources/owlsim2/mock-sim-compare.json
- tests/resources/owlsim2/mock-sim-search.json
- tests/test_phenosim_engine.py
Global max IC is needed for phenogrid, adding metadata field with max_max_ic and updated the tests as needed.  Also added cachier to owlsim calls.
> Add max ic to sim result object

- ontobio/golr/golr_query.py
Currently the `stats` and `stats.field` parameters are ignored when passed to `GolrAssociationQuery`.
This PR adds support for these parameters.
Required for https://github.com/biolink/biolink-api/pull/231
> Add support for stats field

- ontobio/io/ontol_renderers.py
- ontobio/lexmap.py
- ontobio/neo/scigraph_ontology.py
- ontobio/obograph_util.py
- ontobio/ontol.py
- ontobio/slimmer.py
- ontobio/sparql/rdf2nx.py
- ontobio/sparql/sparql_ontol_utils.py
- ontobio/xref_util.py
- requirements.txt
- setup.py
- tests/test_lexmap.py
- tests/test_lexmap_local.py
- tests/test_local_ttl.py
- tests/test_sparql_connection.py
There are a few changes between networkx 1.x and networkx 2.x
This PR upgrades networkx dependency from 1.11 to 2.2.
It also makes the necessary changes across the Ontobio codebase.
**The official migration documentation:** https://networkx.github.io/documentation/stable/release/migration_guide_from_1.x_to_2.0.html
**Lessons learned (an unofficial migration documentation):**
* `graph.nodes_iter()` is now replaced with `graph.nodes()`
* `graph.edges_iter()` is now replaced with `graph.edges()`
* `graph.nodes()` will return an NodeView. Convert this to a list via `list(graph.nodes())`
* `graph.edges()` will return an EdgeDataView. Convert this to a list via `list(graph.edges())`
* `graph.edges()` will return a tuple of edges, `(u,v)`
* `graph.edges(data=True)` will return a 3-tuple, …
> Networkx 2.0 migration

- setup.py
This was causing the annoying security vulnerability warning to appear in some of my repos due to a pyyaml version < 4.2b1 (3.13) being installed through ontobio.
> Upgrade pyyaml req due to vulnerability

- ontobio/ontol_factory.py
- ontobio/sim/api/owlsim2.py
- tests/test_phenosim_engine.py
- tests/unit/test_annotation_scorer.py
- tests/unit/test_owlsim2_api.py
- Uncomments caching in ontology factory
- Moves get_owlsim_stats into module scope instead of class (should I turn the whole thing into a module)?
Fixes https://github.com/biolink/biolink-api/issues/251
> Move get_owlsim_stats out of owlsim api class

- setup.py
We should fix our yaml.load calls -  https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
But in the short term this will allow to run biolink-api
> Specify PyYaml version

- bin/validate.py
If config `compression` field is empty, then we assume no compression.
> allowing unzipped upstream sources

- bin/ontobio-lexmap.py
- bin/validate.py
- ontobio/config.py
- requirements.txt
- setup.py
This PR is as a result of changes in PyYAML 5.1.
Using `yaml.load()` without specifying a loader is not secure.
More details here: https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
This PR depends on https://github.com/dougli1sqrd/yamldown/pull/4
> Fix pyyaml usage

- ontobio/config.yaml
- ontobio/model/association.py
- requirements.txt
- setup.py
This PR just codifies what we've been doing in the dictionary for a long time now. We could do some minimal refactoring over time to convert the parsers and writers to use this Association object rather than the dictionary. This ensures all parsers and writers are on the same page. 
With @dustine32 and I working on the code concurrently where gpad and gafs will need to ensure solid communication, we should have a typed go-between structure. This is just the same as the dictionary, just named now.
This particular PR doesn't change any behavior - Dustin and I will slowly add this in where relevant over time in the parser/writer. @dustine32 if there's anything else we need to add to the model to make your work okay, let's make sure we know about it here. And @cmungall, did I capture your …
> basic skeleton of an internal Association object

- bin/validate.py
- ontobio/io/assocparser.py
- ontobio/io/entityparser.py
- ontobio/io/parsereport.py
`validate.py produce` now has an option `--suppress-rule-tag tag`. This will suppress messages generated from rules with the tag `tag`. Default is no suppression of messages. The canonical thing to do will be to use this with `silent`, which gorule 26 currently has - which will suppress markdown report of rule 26. 
See also https://github.com/geneontology/go-site/issues/884
> command line option to suppress messages from rules with specified tags

- ontobio/io/assocparser.py
A command line message during an ontobio run to show off when we are skipping a rule due to a suppressed tag.
> a log message displaying when we are skipping rule messages

- bin/validate.py
We don't get benefit in the pipeline from cachier in ontology loading as we only load the ontology once per process. Addionally, cachier is hiccuping in the pipeline, so we will attempt to not cache as a solution.
> ontology creation for validate script no longer uses cachier

- ontobio/golr/golr_query.py
This PR addresses the request for adding a field that refers to the aspect of a GO term in an association.
Instead of `aspect` we use `category` to describe what category the GO term belongs to.
This `category` field can have one of three values: 
* `molecular_activity` (F)
* `biological_process` (P)
* `cellular_component` (C)
These values are valid BioLink Model types.
This addition is only applied when associations are fetched from AmiGO/GOlr.
Ex:
```
{
"subject": "UniProtKB:P60484",
"slim": "GO:0008150",
"assocs": [
{
"id": "556e6950726f744b4209503630343834095054454e0909474f3a3030303030373909504d49443a3130393138353639095441530909500950686f73706861746964796c696e6f7369746f6c20332c342c352d7472697370686f73706861746520332d70686f737068617461736520616e64206475616c2d7370656369666963697479207072 …
```
> Adds 'aspect' field to object of an association

- bin/validate.py
This will leave the correct expected files by the pipeline on disk to prevent snapshot sanity check failure. 
@kltm This will be done by the time you're back, but this is just so you can see the historical record.
> copy and rename _valid files rather than just rename

- ontobio/config.yaml
- ontobio/golr/golr_associations.py
- ontobio/golr/golr_query.py
- ontobio/util/scigraph_util.py
This PR adds subject and object `iri` and `category` when fetching associations via golr_query.
CURIE to IRI conversion is done using prefix map as provided by `scigraph-data` instance.
> Return subject and object iri and category when fetching associations

- ontobio/io/assocparser.py
- tests/test_parse_ids.py
Per the changes to gorule 33 to make it report only, this makes no changes to the references.
> rule 33 impl only reports, does not repair

- ontobio/golr/golr_query.py
This PR changes the faceting behavior for queries fired by `GolrAssociationQuery` class.
It removes the default assumption that faceting is always needed.
> Make facet optional in GolrAssociationQuery

- ontobio/golr/golr_query.py
- tests/unit/resources/solr/input/solr-docs.json
- tests/unit/test_golr_search_query.py
Updates highlight code that selects the "best" highlight from a list of matches to a document in solr.  The code now prioritizes primary labels if available, and then looks for the longest match thereafter.  Fixes https://github.com/monarch-initiative/monarch-ui/issues/69
> Prioritize primary label when returning best highlight

- docs/installation.rst
- docs/ontologies_advanced.rst
- ontobio/assoc_factory.py
- ontobio/config.py
- ontobio/config.yaml
- ontobio/ecomap.py
- ontobio/ontol_factory.py
- ontobio/sim/api/owlsim2.py
- ontobio/sparql/sparql_ontol_utils.py
- ontobio/sparql/sparql_ontology.py
- ontobio/sparql/wikidata.py
The cachier caching in Ontobio causes some performance issues in some execution environments (e.g. NCATS Translator Workflow 2): it triggers deep recursion on creating cachier "Observer" threads and stack memory use, sometimes to all available operating system resources!
Disabling cachier in such instances, especially when wholesale retrieval of ontology for local use (once only) is done (as in Workflow 2 above) seems to resolve the issue.
Therefore an "ignore_cache" flag in ontobio/config.yaml (defaults to 'False') can be set to "True". This flag turns off all cachier use in the code base. 
In this fashion, clients of Ontobio can decide whether or not to use the cache for their use cases.
> Introduced "ignore_cache" flag in ontobio/config.yaml (defaults to 'False') 

- docs/inputs.rst
- ontobio/assoc_factory.py
- ontobio/ecomap.py
- ontobio/ontol_factory.py
- ontobio/sim/api/owlsim2.py
- ontobio/sparql/sparql_ontol_utils.py
- ontobio/sparql/wikidata.py
- ontobio/util/scigraph_util.py
- requirements.txt
- setup.py
This PR removes the usage of Cachier from Ontobio.
An alternate caching mechanism will be introduced as a subsequent PR.
Refer to #358 for more on this discussion.
> Remove cachier

- ontobio/golr/golr_query.py
- Remove iri, equivalent_iri in search fields, add taxon_label_synonym
- add option to use a minimal tokenizer, which could be useful for variants and genotypes where the nomenclature contains common punctuation
- add pass through to solr minimum should match param - https://lucene.apache.org/solr/guide/6_6/the-dismax-query-parser.html#TheDisMaxQueryParser-Themm_MinimumShouldMatch_Parameter
> Updates to golr search queries

- Makefile
- bin/validate.py
- ontobio/io/assocparser.py
- ontobio/io/assocwriter.py
- ontobio/io/gafparser.py
- ontobio/validation/rules.py
- tests/test_validation_rules.py
This is for https://github.com/geneontology/go-site/issues/970
This creates a new command for the validate.py script: `rule`. You give it a path to the go-site metadata and an ontology and it will validate the `examples` given in go rules. We made the schema for this a while back. One can add exemplar data that is supposed to `PASS`, `FAIL`, or be `REPAIR`ed. `rule` will create a parser, parse the example data, and compare with what it was expected to get. An example is validated if it matches the state that the example was in. As in: if a gaf line is expected to fail a certain rule, and the parser successfully finds an error for that rule in the given example line, then that example is valid. 
Any invalid example will make the script exit with `1`. This should be used in ontobio travis …
> Go site issue 970 example runner

- ontobio/io/assocparser.py
- ontobio/io/gafparser.py
- tests/test_parse_ids.py
See https://github.com/geneontology/go-site/pull/1197
And https://github.com/geneontology/go-site/issues/1082#issuecomment-556051891
gorule-0000033 will be deprecated, and so we will stop validating on that rule.
> removing validation for gorule-000033 since it was deprecated

- ontobio/golr/golr_query.py
- ontobio/sim/api/owlsim2.py
- ontobio/util/scigraph_util.py
I've made some small updates to support querying direct vs inferred associations by querying the subject/object_eq closures that have been newly added to the monarch solr.  This allows us to support direct queries on non clique leader identifiers, whereas before you were forced to use the subclass of|equivalence closure
Also some updates to support direct vs inferred taxa, although I may walk this back since including inferred taxa is desirable in the majority of cases, and we're only adding this because of some monarch hackiness - https://github.com/monarch-initiative/dipper/issues/860
Support for a generic fq param in biolink is possibly more ideal for these scenarios, but curious others thoughts on this.
> Support for querying for direct vs inferred associations, other fixes for ui

- bin/validate.py
- ontobio/rdfgen/assoc_rdfgen.py
@valearna, @sierra-moxon, in assoc_rdfgen.py line 104 there is a log message for when we expand a CURIE into a URI.
Do you need this in your logs? I will be commenting this out in this PR as it is spamming our logs. Let me know if that messes you up!
Thanks,
Eric
> adding some more logging in validate.py, removed verbose Expand log message

- bin/validate.py
- ontobio/__init__.py
This is a fix for https://github.com/geneontology/go-site/issues/1253
Essentially, this adds a flag to the function that produces validated GAFs. If it's a mixin (like paint_pombase for pombase) then the `mixin` flag is set to `True`.
With mixin set to true, it doesn't generate the same report. This prevents running pombase from producing a `paint_pombase.report.md` which collides with running paint and it's own `paint_pombase.report.md`.
> Go site issue 1253 missing gorule 13

- bin/validate.py
- ontobio/io/assocparser.py
- ontobio/io/qc.py
- tests/test_qc.py
This adds a command line option `--rule-context/-T` to ontobio validate that takes a "rule context".
In the GO Rules, we allow a _tag_ of `context-import` to indicate that the rule should be run during an import pipeline run, but not in an ordinary run.
To specify that a the validation should run the import rule set, the option `-T import` will tell ontobio to run any rule that has the `context-import` tag. When this is not set, rules that have the tag will be skipped. However, they will still appear in the reports as having no errors.
> Issue 427 rulesets

- ontobio/golr/golr_query.py
Adds fq param to GolrSearchQuery to support complex filters. This is needed for the phenotype profile search autocomplete in which we want to filter solr with
(category:phenotype OR (category:gene AND (prefix:HGNC OR has_phenotype:true)) (category:disease AND has_phenotype:true))
> Add fq pass through param to solr search

- ontobio/io/gafparser.py
- tests/resources/test-qualifiers.gaf
- tests/test_gafparser.py
…, filter wrong qualifiers
For https://github.com/geneontology/helpdesk/issues/252
This fixes a bug where malformed qualifiers and wrong qualifiers not allowed were all allowed through the parser with no issue.
Qualifiers with spaces will be repaired with underscores.
> report error if qualifiers are wrong in any way

- Makefile
- bin/ontobio-parse-assocs.py
To run with gaferences, the relavent part is the `-I`.
```
ontobio-parse-assocs.py -f target/groups/mgi/mgi.gaf -F gaf -o target/groups/mgi/mgi.aug.gaf -I mgi.gaferences.json --report-md target/groups/mgi/mgi.report.md --report-json target/groups/mgi/mgi.report.json validate
```
> adding option to give ontobio-parse-assocs a gaf inferences file

- bin/ontobio-parse-assocs.py
- ontobio/io/gpadparser.py
- ontobio/io/hpoaparser.py
Curies were being leaked from an unstringed taxon Curie object into the report. So when we went to turn the report into JSON it broke since the Curie object doesn't know how to be a JSON object. Now Curies are converted into strings before submitted to the report.
> Issue 477 curie leaking

- ontobio/golr/golr_query.py
quick pass at adding support for q param to bioentity queries to support free text search on association documents - for filtering when viewing tables on the monarch app
> add support for q param to golr association fx for monarch

- ontobio/io/gpadparser.py
- setup.py
- tests/test_gpad_parser.py
> gpad parser now takes taxon element out of the list instead of passing on the entire list

- ontobio/io/assocparser.py
- ontobio/io/gafparser.py
- ontobio/io/gpadparser.py
- ontobio/io/qc.py
- ontobio/model/association.py
- setup.py
- tests/test_assoc_writer.py
- tests/test_gafparser.py
- tests/test_goassociation_model.py
- tests/test_qc.py
- tests/test_rdfgen.py
Uses the `date` variable, normalized with date format (YYYYMMDD), for internal GORULE tests rather than just passing through raw column value `gpad_line[8]`
> Pass normalized date to GoAssoc for #493

- ontobio/io/qc.py
- tests/test_gafparser.py
- tests/test_qc.py
This is the ontobio implementation for gorule-0000061.
The only thing tricky about this was handling identifying which tree of the ontology a GO term belonged to. In general I use the `OIO:hasOBONamespace` which *is* consistently defined for the ontology today.
But mostly in tests, there are some json ontologies that do not use this to identify the "namespace" of a term. I have chosen to think of a missing namespace as essentially "missing ontology". Presently, in the rules, the policy is to automatically pass any rule that does not have an attached ontology. This way rules that rely on the ontology can just be skipped if one isn't provided for whatever reason. The option to provide an ontology has been pretty historical in the code, although more current tooling *requires* an ontology in …
> gorule 61 implementation in ontobio

- bin/ontobio-parse-assocs.py
- bin/validate.py
- docs/commandline.rst
- ontobio/io/assocparser.py
- ontobio/io/qc.py
- tests/test_gafparser.py
- tests/test_qc.py
For https://github.com/biolink/ontobio/issues/544
> Issue 544 rulesets

- ontobio/golr/golr_query.py
- ontobio/model/GolrResults.py
- tests/unit/resources/solr/expected/autocomplete-nocat.json
- tests/unit/resources/solr/expected/autocomplete.json
- tests/unit/test_golr_search_query.py
Adds support for filtering in/out a prefix in a equivalent curie as well as filtering for only leaf nodes. See https://github.com/biolink/biolink-api/issues/368
> solr search query add support for filtering based on equivalent curie prefix, leaf nodes

- ontobio/golr/golr_query.py
- tests/unit/test_golr_search_query.py
Update to PR #550, adding a colon to the prefix filter to avoid cases like OMIM, OMIMPS
> tweak to #550 - add colon to wildcard query

- ontobio/rdfgen/gocamgen/gocamgen.py
- ontobio/rdfgen/relations.py
For #572.
I also changed how missing extension relation errors are handled. This change now skips translating only the offending extension (e.g. `RO:0002491(GO:0098768)`) whereas the old code would skip translating the entire ~~annotation~~ _model for the gene_. The error is still being reported out.
> Updated to new RO term and relaxed error handling for missing ext rel

- ontobio/io/gpadparser.py
- tests/test_gpad_parser.py
> Repair obsolete terms before other GO rule tests; for #576

- requirements.txt
> Add missing chardet dependency for PyShEx. For #578

- ontobio/rdfgen/relations.py
This is part of the work to transition from using 'exists during' as a GOREL relation to using appropriate temporal relations from RO.
Note that the current entry for 'exists during' refers to RO:0002491 whose label is actually 'existence starts and ends during'.  We should also clean this up at some point, as 'exists during' as a term label currently only exists in gorel.obo for GOREL:0000032.
@dustine32 @kltm - if we updated the entries for 'exists during' (i.e. change to GOREL id) to point to the GOREL id, would that break anything?  I would also then add the correct RO entry for 'existence starts and ends during'.
> Adding 'existence overlaps' RO relation

- ontobio/obograph_util.py
- requirements.txt
This PR,
- replaces the usage of a deprecated networkx method `graph.node` with `graph.nodes` in `obograph_util.py`.
- removes the pinning of networkx dependency
@matentzn Thanks for raising this issue again. Hopefully the next release should get rid of the fixed dependency
> Fix bug in obograph_utils by replacing the usage of deprecated networkx methods

- ontobio/config.py
- requirements.txt
This PR proposes to unpin `marshmallow` so that `ontobio` does not depend on a beta release dating from 2018.
That pinned dependency creates an unsolvable conflict in the [ODK](https://github.com/INCATools/ontology-development-kit), which uses both `ontobio` (requiring `marshmallow==3.0.0b11`) and `dataclasses-json` (requiring `marshmallow>=3.3.0`).
`marshmallow` is the last pinned dependency, so unpinning it would close #482.
> Unpin marshmallow

- ontobio/sim/api/owlsim2.py
The latest monarch release includes Xenopus laevus and tropicalus grouped under the taxon 8353.  This will allow users to query owlsim and specifically target Xenopus genes (with XPO terms or any other phenotype in UPheno)
> Add Xenbase taxon map to owlsim 

- ontobio/golr/golr_query.py
Currently, the biolink-api endpoint `/search/entity/{term}` returns just taxon labels in the `facet_counts. taxon_label` subkey, but other endpoints' filtering arguments require taxon IDs, not labels. Because of this, the Monarch frontend requires a map from taxon label to taxon ID, but ideally this data would come from the backend.
This PR adds an optional, but by default enabled facet to the results of `ontobio.golr.GolrSearchQuery`, specifically a subkey called `_taxon_map` with the following form:
```
"_taxon_map": [
{
"id": <taxon ID:str>,
"label": <taxon label:str>,
"count": <count:int>
},
...
]
```
The extra facet can be disabled by passing `taxon_map=False` to `ontobio.golr.GolrSearchQuery`'s constructor.
Addresses https://github.com/biolink/biolink-api/issues/386.
> Adds _taxon_map subkey to GolrSearchQuery result

- ontobio/io/gpadparser.py
- tests/unit/test_golr_search_query.py
Fixes geneontology/pipeline#280.
Specifically, the aspect rule test ([GORULE:0000028](https://github.com/geneontology/go-site/tree/master/metadata/rules#aspect-can-only-be-one-of-c-p-f-and-should-be-repaired-using-the-go-term)) will still run for GPAD and repair the empty `GoAssociation.aspect` (this is how aspect is sourced when merging `noctua_{group}.gpad` into `{group}.gaf`) but the reports will no longer reflect failure.
> Ignore GORULE:0000028 aspect check when parsing GPAD

- bin/ontobio-parse-assocs.py
- ontobio/io/gpadparser.py
For #620.
Quick fix to handle GO pipeline run context as explained here https://github.com/geneontology/go-site/issues/1847#issuecomment-1120020146
> Lock down evaluating allow_unmapped_eco defaults

- ontobio/golr/golr_query.py
will fix https://github.com/geneontology/helpdesk/issues/285 when go-fastapi becomes production (if we upgraded go-api with this library change it would be fixed as well; best to keep the issue open(?) until go-fastapi goes to prod).
> remove object from map to prevent accidental removal from fq parameter 

- ontobio/model/collections.py
- tests/test_collections.py
For geneontology/go-releases#50.
This fleshes out the `collections.BioEntities.merge()` function to better handle labels when some are blank. The entity label should only be overwritten if the new label is non-blank.
In our actual use case here:
1. The GAF-derived GPI is parsed into `BioEntities` first.
2. The upstream, canonical MOD GPI is parsed and its own `BioEntities` object.
3. The upstream, canonical MOD GPI `BioEntities` are merged into the existing GAF-derived GPI `BioEntities` ensuring that, if the canonical GPI has a blank symbol, it does not clobber the existing non-blank symbol.
> Handle GPI label merge for geneontology/go-releases#50

- ontobio/io/qc.py
- tests/resources/goslim_generic.json
- tests/test_qc.py
Change corresponds to geneontology/go-site#2002. Slight correction of initial PR https://github.com/biolink/ontobio/pull/646.
This fixes a bug introduced with https://github.com/biolink/ontobio/pull/646 that was failing all obsoleted terms in rule 61 because their ontology node did not have a `namespace` key:
https://github.com/biolink/ontobio/blob/6a9924a1295f896dfdf6df5796a9e1b6d1203df9/ontobio/io/qc.py#L907
An example obsoleted term is GO:1902361. The failed GO rule test example is here: https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000020.md
I added a test for this (within `ontobio`!!) under rule 61 and confirmed that the `go-site` [test suite](https://github.com/geneontology/go-site/blob/master/scripts/rule-example-validation.sh) (really just a wrapper …
> Reverting FAIL to OKAY since obsolete terms have no namespace

- ontobio/io/qc.py
- tests/test_qc.py
Updated to ensure that annotations with evidence code 'IC' have a GO Id entry in the 'with/from' field that is different from the GO Id for the annotation
> For #1523 check for unique GO ID

- ontobio/io/qc.py
- tests/test_qc.py
For geneontology/go-site#2185. Updates GoRule test to look for correct `GO_REF:0000033` (with underscore) in IBA annotations.
This was meant to be coordinated with the generation of IBA GAF files after https://github.com/pantherdb/fullgo_paint_update/commit/c0587f299e98c1a909ca317b21c7556892cea033 but this should now be merged ASAP.
> Add underscore to GO_REF:0000033

- ontobio/io/gafparser.py
- tests/test_gafparser.py
For #2064 - gorule-0000001 check for pipe in gene symbol
> For #2064 - Added check for pipe in gene symbol

- bin/README.md
- bin/validate.py
- tests/test_gafparser.py
- tests/test_gpad_parser.py
see: https://github.com/geneontology/pipeline/issues/387#issuecomment-2471589993
> Issue pipeline 387 - add GAF header information to aggregated GPAD produced by megamake step (aka. ontobio/bin/validate.py) 
